sources:
  - name: bronze
    database: pyspark_dbt  
    schema: bronze  
    tables:
      - name: trips
  

  - name: silver
    database: pyspark_dbt  
    schema: silver  
    tables:
      - name: customers
      - name: locations
      - name: drivers
      - name: payments
      - name: vehicles
      - name: trips
            


  